CC     = g++
CFLAGS = -g -Wall
 
all: VoteApp
 
VoteApp: ./core/Interfaz.cpp ./core/Runable.cpp ./core/VoteApp.cpp ./estructuras/File.cpp ./estructuras/Uint32Key.cpp  ./managers/AdmministratorFile.cpp ./managers/CandidateFile.cpp ./managers/ElectionFile.cpp ./managers/ChargeFile.cpp ./managers/DistrictFile.cpp ./managers/ListFile.cpp ./managers/VoteCountingFile.cpp ./managers/VoterFile.cpp ./records/AdministratorRecord.cpp ./records/CandidateKey.cpp ./records/CandidateRecord.cpp ./records/ChargeKey.cpp ./records/ChargeRecord.cpp ./records/DistrictRecord.cpp ./records/ElectionKey.cpp ./records/ElectionRecord.cpp ./records/ListKey.cpp ./records/ListRecord.cpp ./records/StringKey.cpp ./records/VoteCountingKey.cpp ./records/VoteCountingRecord.cpp ./records/VoterRecord.cpp ./screens/AdministratorScreen.cpp ./screens/ChargeScreen.cpp ./screens/ElectionScreen.cpp ./screens/ListScreen.cpp ./screens/LoginScreen.cpp ./screens/ResultScreen.cpp ./screens/SimulScreen.cpp ./utils/IstreamUtils.cpp ./utils/Logger.cpp ./utils/StringUtils.cpp ./utils/Time.cpp 
	$(CC) $(CFLAGS) -o VoteApp ./core/Interfaz.cpp ./core/Runable.cpp ./core/VoteApp.cpp ./estructuras/File.cpp ./estructuras/Uint32Key.cpp  ./managers/AdmministratorFile.cpp ./managers/CandidateFile.cpp ./managers/ElectionFile.cpp ./managers/ChargeFile.cpp ./managers/DistrictFile.cpp ./managers/ListFile.cpp ./managers/VoteCountingFile.cpp ./managers/VoterFile.cpp ./records/AdministratorRecord.cpp ./records/CandidateKey.cpp ./records/CandidateRecord.cpp ./records/ChargeKey.cpp ./records/ChargeRecord.cpp ./records/DistrictRecord.cpp ./records/ElectionKey.cpp ./records/ElectionRecord.cpp ./records/ListKey.cpp ./records/ListRecord.cpp ./records/StringKey.cpp ./records/VoteCountingKey.cpp ./records/VoteCountingRecord.cpp ./records/VoterRecord.cpp ./screens/AdministratorScreen.cpp ./screens/ChargeScreen.cpp ./screens/ElectionScreen.cpp ./screens/ListScreen.cpp ./screens/LoginScreen.cpp ./screens/ResultScreen.cpp ./screens/SimulScreen.cpp ./utils/IstreamUtils.cpp ./utils/Logger.cpp ./utils/StringUtils.cpp ./utils/Time.cpp  
 

